-- uat/erp - orcl


-- select * from ZG_ERP.TSUPPLIER_SIGN_INFO;

-- 创建表
CREATE TABLE ZG_ERP.TSUPPLIER_SIGN_INFO (
	PKID NUMBER,
	SUPPLIER_ID NUMBER(10,0),
	SUPPLIER_NAME VARCHAR2(100),
	SIGN_TIME DATE,
	FIRST_START_USING_TIME DATE,
	FIRST_STOP_ALL_TIME DATE,
	CREATE_TIME DATE,
	CREATE_BY VARCHAR2(100),
	LAST_MODIFIED_TIME DATE,
	LAST_MODIFIED_BY VARCHAR2(100),
	VALID CHAR(1)
);
COMMENT ON TABLE ZG_ERP.TSUPPLIER_SIGN_INFO IS '供应商新签时间、首次启用时间、首次全关停时间等信息';
COMMENT ON COLUMN ZG_ERP.TSUPPLIER_SIGN_INFO.PKID IS '主键id';
COMMENT ON COLUMN ZG_ERP.TSUPPLIER_SIGN_INFO.SUPPLIER_ID IS '供应商id';
COMMENT ON COLUMN ZG_ERP.TSUPPLIER_SIGN_INFO.SUPPLIER_NAME IS '供应商名称';
COMMENT ON COLUMN ZG_ERP.TSUPPLIER_SIGN_INFO.SIGN_TIME IS '新签时间';
COMMENT ON COLUMN ZG_ERP.TSUPPLIER_SIGN_INFO.FIRST_START_USING_TIME IS '首次二级启用时间';
COMMENT ON COLUMN ZG_ERP.TSUPPLIER_SIGN_INFO.FIRST_STOP_ALL_TIME IS '首次二级全关停时间';
COMMENT ON COLUMN ZG_ERP.TSUPPLIER_SIGN_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN ZG_ERP.TSUPPLIER_SIGN_INFO.CREATE_BY IS '创建人';
COMMENT ON COLUMN ZG_ERP.TSUPPLIER_SIGN_INFO.LAST_MODIFIED_TIME IS '最后修改时间';
COMMENT ON COLUMN ZG_ERP.TSUPPLIER_SIGN_INFO.LAST_MODIFIED_BY IS '最后修改时间';
COMMENT ON COLUMN ZG_ERP.TSUPPLIER_SIGN_INFO.VALID IS '是否有效';

-- 创建序列
CREATE SEQUENCE SQ_TSUPPLIER_SIGN_INFO
INCREMENT BY 1 
MINVALUE 10000000
MAXVALUE 900000000
cache 20;
