select * from ZG_ERP.TSUPPLIER_SIGN_INFO;

-- 生成随机数据
INSERT INTO ZG_ERP.TSUPPLIER_SIGN_INFO
(PKID, SUPPLIER_ID, SUPPLIER_NAME, SIGN_TIME, FIRST_START_USING_TIME, FIRST_STOP_ALL_TIME, CREATE_TIME, CREATE_BY, LAST_MODIFIED_TIME, LAST_MODIFIED_BY, VALID)
VALUES(SQ_TSUPPLIER_SIGN_INFO.NEXTVAL, 0, 'SQL', SYSDATE -3 , SYSDATE -2 , SYSDATE -1 , SYSDATE -1 , 'SQL',SYSDATE -1 , 'SQL', 'T');
